### ISSUE TITLE
Simplified 'project description' on PYPI

### ISSUE THREAD

**Issue by xlcnd** [arangb/isbnlib-mcues#2]
Could you change the *Project description* of https://pypi.org/project/isbnlib-mcues/, from 

> A plugin for isbnlib that pulls metadata from Ministerio de Cultura (Spain) http://www.mcu.es/webISBN/tituloSimpleFilter.do?cache=init&prev_layout=busquedaisbn&layout=busquedaisbn&language=es.

to 

> A plugin for isbnlib that pulls metadata from Ministerio de Cultura (Spain).?

It makes the output of `pip search` easier to read.

**Comment by arangb** [comment]
Fixed in v.0.0.2, now released in PyPi.
